### ISSUE TITLE
Error performing request: PUT https://xxx.xxx.xx.xx  :dial tcp timedout. While Running Cedar Script with 100 batches

### ISSUE THREAD

**Issue by ghost** [cloudfoundry/diego-perf-release#7]
Hello,
To perform a load test of 25k instances I configured to 100 batches  and when I run the cedar script, upto 10k applications were deployed and after that facing the following issue.

**+ cf set-quota perf_org perf
Setting quota perf to org perf_org as admin...
FAILED
Error performing request: Put https://api.xxxx.xxx.xxx.xx.: dial tcp xx.xx.xx.xx: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.**

I couldn't find the exact cause for this issue.. Can you please update on it.

Thanks and Regards,
Kesavan

**Comment by emalm** [comment]
Hi, @K7king,

From the form of the error, it sounds like the CF CLI was unable to connect to the Cloud Controller for that particular command. That issue does not seem directly related to the diego-perf-release, but it's possible that the load it puts on the system contributes to these failures. Do you know whether this is an ongoing problem, such that in general you cannot connect to Cloud Controller via CF CLI commands or via HTTP clients such as `curl`?

Thanks,
Eric

**Comment by ghost** [comment]
Hai @emalm ,
              Yes this is an ongoing problem.Cloud controller can't able to connect to CF CLI but GET Request on api give results.We  are trying to scale different components to find the bottleneck.

Thanks and Regards,
Kesavan.

**Comment by emalm** [comment]
Hi, @K7king, since this sounds like a problem with the scale of your target CF environment and not the Diego performance release itself, I'll close out this issue.

Best,
Eric
