### ISSUE TITLE
fail to generate deployment manifest

### ISSUE THREAD

**Issue by eujungkim** [cloudfoundry/diego-perf-release#8]
I'm using diego version 1.26.2.
So I don't have neither diego.yml nor bbs vm.
I have some troubles to run script/generate-deployment-manifest.
Can I have sample deployment manifest or guide for newer cf version?

**Comment by emalm** [comment]
Hi, @eujungkim, sorry for letting this issue sit unattended over the past few weeks. The [manifest-generation script](https://github.com/cloudfoundry/diego-perf-release/blob/master/scripts/generate-deployment-manifest) in this release is designed to work with the separate CF and Diego BOSH manifests generated from [cf-release](https://github.com/cloudfoundry/cf-release/blob/master/scripts/generate_deployment_manifest) and [diego-release](https://github.com/cloudfoundry/diego-release/blob/develop/scripts/generate-deployment-manifest), respectively. If you don't have these manifests available, how have you deployed your CF cluster? Are you using [cf-deployment](https://github.com/cloudfoundry/cf-deployment) instead?

Thanks,
Eric, CF Diego PM

**Comment by eujungkim** [comment]
@emalm  Yes. I'm using cf-deployment.
Can I have sample deployment manifest or guide for cf-deployment?

**Comment by emalm** [comment]
Hi, @eujungkim, we hadn't yet prioritized updating the manifest generation system for this release to work with the cf-deployment manifest, but we now have a story at https://www.pivotaltracker.com/story/show/154181336 to do so (likely via an operations file similar to the one at https://github.com/cloudfoundry/diego-release/blob/develop/operations/add-vizzini-errand.yml that adds an instance group to run the Vizzini test suite).

Best,
Eric

**Comment by emalm** [comment]
Hi, @eujungkim, we've added an operations file at https://github.com/cloudfoundry/diego-perf-release/blob/master/operations/add-diego-perf-release.yml that you can use to add a perf-release instance to your cf-deployment-based CF deployment.

Best,
Eric
