### ISSUE TITLE
Enhancing  Diego-Perf-Release : Proposal

### ISSUE THREAD

**Issue by ghost** [cloudfoundry/diego-perf-release#9]
We are using the Diego Stress Test to validate some of our deployment scenarios. As the current scope of the Diego Stress Test is mostly focused on the scalability of the platform, we would like to contribute to enhance the scope of the tests even further. Below are the proposals:
 
**Stress-App:**
As the current Stress-App is designed to do a simple Curl request to itself, we would like to enhance this by making the app more realistic by adding some Disk I/O to make the app either CPU or memory bound.
 
In a nutshell, we would imagine the following capabilities of the stress-app configurable via environment variables:
 
-	Create https requests to itself in a configurable interval (already supported)
-	Create logs in a configurable interval (already supported)
-	Crash in a given interval (already supported)
-	Make TLS validation of self-curl configurable to support foundations (mainly CI test deployments) with invalid certificates (new)

-	Consume/Commit container memory in a configurable size (new)
-	Write/Read files to/from the container file system in a configurable size (new)
-	Trigger CPU-intensive work to let apps on the same host compete for resources (new)
 
**Backing Services:**
It would be a good idea to include few backing services and using this backing services in the stress-app to do basic CRUD operations.
Since every foundation comes with a different set of backing services this has to be optional and highly configurable.

**Comment by heyjcollins** [comment]
Given our current priorities and available resources we're not in a position to resolve this issue, and given it's been idle for quite some time, I'm going to go ahead a close it out.
